[package]
name = "json5_parser_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
json5_parser = { path = "../json5_parser" }
serde-wasm-bindgen = "0.6.3"
wasm-bindgen = { version = "0.2.91" }
